_BASE_: "../Base-RCNN.yaml"
MODEL:
  WEIGHTS: "ImageNetPretrained/MSRA/R-101.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  RPN:
    ENABLE_DECOUPLE: True
    BACKWARD_SCALE: 0.0
  ROI_HEADS:
    NAME: "Res5ROIHeads"
    NUM_CLASSES: 21
    NUM_KNOWN_CLASSES: 15
    NUM_BASE_CLASSES: 10
    ENABLE_DECOUPLE: True
    BACKWARD_SCALE: 0.75
  ROI_BOX_HEAD:
#    NAME: "FastRCNNSeparateConvFCHead"
    OUTPUT_LAYERS: "FOODFastRCNNOutputLayers"
    CLS_AGNOSTIC_BBOX_REG: True
#    FC_DIM: 2048
#    BBOX_REG_LOSS_TYPE: giou
#      BBOX_REG_LOSS_TYPE: smooth_l1
INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  MIN_SIZE_TEST: 800
DATASETS:
  TRAIN: ('voc_2007_trainval_base1', 'voc_2012_trainval_base1')
  TEST: ('voc_2007_test_base1',)
SOLVER:
  IMS_PER_BATCH: 8
  STEPS: (35000, 42000)
  MAX_ITER: 500000
  CHECKPOINT_PERIOD: 5000
  WARMUP_ITERS: 100
  BASE_LR: 0.01
UPLOSS:
  ENABLE_UPLOSS: False
  START_ITER: 0
  SAMPLING_METRIC: "edl_dirichlet"
  TOPK: 3
  SAMPLING_RATIO: 1
  ALPHA: 1.0
  WEIGHT: 1.0
ELOSS:
  ENABLE_ELOSS: False
  WEIGHT: 0.1
HSICLOSS:
  ENABLE_HSICLOSS: False
ICLOSS:
  OUT_DIM: 2048
  QUEUE_SIZE: 32
  IN_QUEUE_SIZE: 16
  BATCH_IOU_THRESH: 0.5
  QUEUE_IOU_THRESH: 0.7
  TEMPERATURE: 0.1
  WEIGHT: 0.1
TEST:
  EVAL_PERIOD: 5000
OUTPUT_DIR: "/home/user/xinzhimeng/desk1/FOOD/r101"